// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Game$ReactHooksTemplate = require("./Game.bs.js");

function App(Props) {
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "title"
                }, "Tic Tac Toe"), React.createElement(Game$ReactHooksTemplate.make, { }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
