// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Component1$ReactHooksTemplate = require("./Component1.bs.js");
var Component2$ReactHooksTemplate = require("./Component2.bs.js");

function App(Props) {
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "title"
                }, "Tic Tac Toe"), React.createElement(Component1$ReactHooksTemplate.make, {
                  message: "Hello! Click this text."
                }), React.createElement(Component2$ReactHooksTemplate.make, {
                  greeting: "Hello!"
                }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
