// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Square$ReactHooksTemplate = require("./Square.bs.js");

function Board(Props) {
  var squares = Props.squares;
  var onClickSquare = Props.onClickSquare;
  var renderSquare = function (i) {
    return React.createElement(Square$ReactHooksTemplate.make, {
                value: Caml_array.caml_array_get(squares, i),
                onClick: (function (_event) {
                    return Curry._1(onClickSquare, i);
                  })
              });
  };
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "board-row"
                }, renderSquare(0), renderSquare(1), renderSquare(2)), React.createElement("div", {
                  className: "board-row"
                }, renderSquare(3), renderSquare(4), renderSquare(5)), React.createElement("div", {
                  className: "board-row"
                }, renderSquare(6), renderSquare(7), renderSquare(8)));
}

var make = Board;

exports.make = make;
/* react Not a pure module */
