// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Square$ReactHooksTemplate = require("./Square.bs.js");

function renderSquare(i) {
  return React.createElement(Square$ReactHooksTemplate.make, {
              value: i
            });
}

function Board(Props) {
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "status"
                }, "Next player: X"), React.createElement("div", {
                  className: "board-row"
                }, renderSquare(0), renderSquare(1), renderSquare(2)), React.createElement("div", {
                  className: "board-row"
                }, renderSquare(3), renderSquare(4), renderSquare(5)), React.createElement("div", {
                  className: "board-row"
                }, renderSquare(6), renderSquare(7), renderSquare(8)));
}

var make = Board;

exports.renderSquare = renderSquare;
exports.make = make;
/* react Not a pure module */
