// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");
var Board$ReactHooksTemplate = require("./Board.bs.js");
var StartNewGameButton$ReactHooksTemplate = require("./StartNewGameButton.bs.js");

var winningCombinations = /* :: */[
  /* :: */[
    0,
    /* :: */[
      1,
      /* :: */[
        2,
        /* [] */0
      ]
    ]
  ],
  /* :: */[
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ],
    /* :: */[
      /* :: */[
        6,
        /* :: */[
          7,
          /* :: */[
            8,
            /* [] */0
          ]
        ]
      ],
      /* :: */[
        /* :: */[
          0,
          /* :: */[
            3,
            /* :: */[
              6,
              /* [] */0
            ]
          ]
        ],
        /* :: */[
          /* :: */[
            1,
            /* :: */[
              4,
              /* :: */[
                7,
                /* [] */0
              ]
            ]
          ],
          /* :: */[
            /* :: */[
              2,
              /* :: */[
                5,
                /* :: */[
                  8,
                  /* [] */0
                ]
              ]
            ],
            /* :: */[
              /* :: */[
                0,
                /* :: */[
                  4,
                  /* :: */[
                    8,
                    /* [] */0
                  ]
                ]
              ],
              /* :: */[
                /* :: */[
                  2,
                  /* :: */[
                    4,
                    /* :: */[
                      6,
                      /* [] */0
                    ]
                  ]
                ],
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

function calculateWinner(squares, _lines) {
  while(true) {
    var lines = _lines;
    if (lines) {
      var row = lines[0];
      var exit = 0;
      if (row) {
        var match = row[1];
        if (match) {
          var match$1 = match[1];
          if (match$1 && !match$1[1]) {
            var a = row[0];
            var match$2 = Caml_array.caml_array_get(squares, a) !== "" && Caml_array.caml_array_get(squares, a) === Caml_array.caml_array_get(squares, match[0]) && Caml_array.caml_array_get(squares, a) === Caml_array.caml_array_get(squares, match$1[0]);
            if (match$2) {
              return Caml_array.caml_array_get(squares, a);
            } else {
              _lines = lines[1];
              continue ;
            }
          } else {
            exit = 1;
          }
        } else {
          exit = 1;
        }
      } else {
        exit = 1;
      }
      if (exit === 1) {
        throw [
              Caml_builtin_exceptions.match_failure,
              /* tuple */[
                "Game.re",
                16,
                8
              ]
            ];
      }
      
    } else {
      return "";
    }
  };
}

function Game(Props) {
  var match = React.useState((function () {
          return /* array */[Caml_array.caml_make_vect(9, "")];
        }));
  var setHistory = match[1];
  var history = match[0];
  var match$1 = React.useState((function () {
          return true;
        }));
  var setXNext = match$1[1];
  var xNext = match$1[0];
  var currentBoard = Caml_array.caml_array_get(history, history.length - 1 | 0);
  var winner = calculateWinner(currentBoard, winningCombinations);
  var match$2 = winner !== "";
  var status = match$2 ? "The winner is " + winner : "Next player: " + (
      xNext ? "X" : "O"
    );
  var moves = $$Array.mapi((function (step, move) {
          var match = step > 0;
          var description = match ? "Go back to round " + String(step) : "Go back to beginning";
          return React.createElement("li", undefined, React.createElement("button", {
                          onClick: (function (_event) {
                              var i = step;
                              var match = i > 0;
                              var historyReturnedTo = match ? $$Array.sub(history, 0, i) : /* array */[Caml_array.caml_make_vect(9, "")];
                              return Curry._1(setHistory, (function (param) {
                                            return historyReturnedTo;
                                          }));
                            })
                        }, description));
        }), history);
  var handleClick = function (i) {
    var newSquares = $$Array.copy(currentBoard);
    if (winner !== "" || Caml_array.caml_array_get(currentBoard, i) !== "") {
      return /* () */0;
    } else {
      Caml_array.caml_array_set(newSquares, i, xNext ? "X" : "O");
      Curry._1(setHistory, (function (his) {
              return $$Array.append(his, /* array */[newSquares]);
            }));
      return Curry._1(setXNext, (function (xNext) {
                    return !xNext;
                  }));
    }
  };
  var startNewGame = function (param) {
    Curry._1(setXNext, (function (param) {
            return true;
          }));
    return Curry._1(setHistory, (function (param) {
                  return /* array */[Caml_array.caml_make_vect(9, "")];
                }));
  };
  var match$3 = winner !== "";
  return React.createElement("div", {
              className: "game"
            }, React.createElement("div", {
                  className: "game-board"
                }, React.createElement(Board$ReactHooksTemplate.make, {
                      squares: currentBoard,
                      onClickSquare: handleClick
                    })), React.createElement("div", {
                  className: "game-info"
                }, React.createElement("div", undefined, status), React.createElement("ol", undefined, moves)), match$3 ? React.createElement(StartNewGameButton$ReactHooksTemplate.make, {
                    startNewGame: startNewGame
                  }) : null);
}

var make = Game;

exports.winningCombinations = winningCombinations;
exports.calculateWinner = calculateWinner;
exports.make = make;
/* react Not a pure module */
