// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Square(Props) {
  var value = Props.value;
  var onClick = Props.onClick;
  return React.createElement("button", {
              className: "square",
              onClick: onClick
            }, value);
}

var make = Square;

exports.make = make;
/* react Not a pure module */
