// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Square(Props) {
  var value = Props.value;
  var onHandleClick = Props.onHandleClick;
  return React.createElement("button", {
              className: "square",
              onClick: onHandleClick
            }, value);
}

var make = Square;

exports.make = make;
/* react Not a pure module */
